version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_notas
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sistema_notas
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - notas_net

  app:
    build: .
    container_name: notas_backend
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=1234
      - DB_NAME=sistema_notas
      - DB_DIALECT=mysql
    depends_on:
      - mysql
    networks:
      - notas_net

networks:
  notas_net:
    driver: bridge